version: '2'
services:
  app:
    build: .
    ports:
      - "80:80"
    links:
      - redis
    image: bbhalki1/kitten_counter
  redis:
    image: redis
  worker:
        build:
            context: .
            dockerfile: Dockerfile